name: CI-BlackDuck-SCA-Basic-DeanTest
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled, assigned, unassigned]
    
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source step
        uses: actions/checkout@v4
      - name: Black Duck Scan step
        id: black-duck-security-scan
        uses: blackduck-inc/black-duck-security-scan@v2.1.0
        
        ### Configure DETECT environment variables
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          
        with:
          ### SCANNING: Required fields
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
         
          ### SCANNING: Optional fields
          # blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'
          
          ### FIX PULL REQUEST CREATION: Uncomment below to enable
          # blackducksca_fixpr_enabled: true
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when Fix PRs is enabled
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          # blackducksca_prcomment_enabled: true 
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled

          ### SARIF report generation and upload to GitHub Adavanced Security: Uncomment below to enable
          # blackducksca_reports_sarif_create: true # Create Black Duck SARIF report and upload it as artifact
          # blackducksca_upload_sarif_report: true  # Upload Black Duck SARIF report in GitHub Advanced Security tab
          
          ### Mark build status if policy violating issues are found
          # mark_build_status: 'success'
          
          ### Uncomment below configuration to add custom logic based on return status
      - name: cmdLine                  
        id: cmdLine
        run: |
          EXIT_CODE=${{ steps.black-duck-security-scan.outputs.status }}
          echo "Black Duck Security Scan exit status - $EXIT_CODE"
